const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.filechooser,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.List,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.JavaScriptInEvents.EventSheet1_Event1_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event2_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event3_Act1,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.JavaScriptInEvents.EventSheet1_Event4_Act2,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Exps.SelectedText,
		C3.JavaScriptInEvents.EventSheet1_Event12_Act1,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.EventSheet1_Event13_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event15_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.List.Acts.SetPos,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.filechooser.Acts.SetPos,
		C3.JavaScriptInEvents.EventSheet1_Event25_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event26_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event27_Act1,
		C3.JavaScriptInEvents.EventSheet1_Event28_Act1,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.JavaScriptInEvents.Previewevents_Event1_Act1,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Previewevents_Event20_Act1,
		C3.JavaScriptInEvents.Loginevents_Event1_Act1,
		C3.Plugins.Audio.Acts.Play,
		C3.JavaScriptInEvents.Loginevents_Event2_Act2,
		C3.JavaScriptInEvents.Loginevents_Event3_Act2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.JavaScriptInEvents.Loginevents_Event10_Act7,
		C3.JavaScriptInEvents.Menuevents_Event1_Act1,
		C3.JavaScriptInEvents.Menuevents_Event2_Act1,
		C3.JavaScriptInEvents.Menuevents_Event5_Act1,
		C3.JavaScriptInEvents.Menuevents_Event8_Act1,
		C3.JavaScriptInEvents.Menuevents_Event9_Act1,
		C3.JavaScriptInEvents.Menuevents_Event15_Act2,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.filechooser.Acts.Clear,
		C3.JavaScriptInEvents.Menuevents_Event16_Act2,
		C3.JavaScriptInEvents.Menuevents_Event18_Act7,
		C3.JavaScriptInEvents.Betaevents_Event1_Act1,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.JavaScriptInEvents.Betaevents_Event7_Act7,
		C3.JavaScriptInEvents.Monetizeevents_Event1_Act1,
		C3.JavaScriptInEvents.Monetizeevents_Event5_Act2,
		C3.JavaScriptInEvents.Monetizeevents_Event6_Act2,
		C3.JavaScriptInEvents.Monetizeevents_Event9_Act1,
		C3.JavaScriptInEvents.Monetizeevents_Event10_Act3,
		C3.JavaScriptInEvents.Monetizeevents_Event11_Act3,
		C3.JavaScriptInEvents.Monetizeevents_Event13_Act7,
		C3.JavaScriptInEvents.Advertiseevents_Event1_Act1,
		C3.JavaScriptInEvents.Advertiseevents_Event1_Act2,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.JavaScriptInEvents.Advertiseevents_Event2_Act1,
		C3.Plugins.Button.Cnds.IsOnScreen,
		C3.JavaScriptInEvents.Advertiseevents_Event11_Act1,
		C3.Plugins.List.Cnds.CompareSelectedText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.JavaScriptInEvents.Advertiseevents_Event30_Act1,
		C3.JavaScriptInEvents.Advertiseevents_Event32_Act2,
		C3.Plugins.filechooser.Acts.Click,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Advertiseevents_Event44_Act2,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.List.Cnds.IsOnScreen,
		C3.JavaScriptInEvents.Advertiseevents_Event52_Act2,
		C3.JavaScriptInEvents.Advertiseevents_Event53_Act2,
		C3.JavaScriptInEvents.Advertiseevents_Event55_Act7,
		C3.JavaScriptInEvents.Dashboardevents_Event1_Act1,
		C3.JavaScriptInEvents.Dashboardevents_Event2_Act1,
		C3.JavaScriptInEvents.Dashboardevents_Event3_Act2,
		C3.JavaScriptInEvents.Dashboardevents_Event5_Act2,
		C3.JavaScriptInEvents.Dashboardevents_Event11_Act1,
		C3.JavaScriptInEvents.Dashboardevents_Event14_Act1,
		C3.JavaScriptInEvents.Dashboardevents_Event15_Act1,
		C3.JavaScriptInEvents.Dashboardevents_Event20_Act1,
		C3.JavaScriptInEvents.Dashboardevents_Event21_Act2,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.Dashboardevents_Event22_Act4,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.OnURLLoaded
	];
};
self.C3_JsPropNameTable = [
	{Button_create_ad: 0},
	{TextInput_AdClickUrlInput: 0},
	{Button_fetch_next_ad: 0},
	{Button_PurchaseViews: 0},
	{Button_show_all_ads: 0},
	{FileChooser_AdImage: 0},
	{TextInput_AdViewsInput: 0},
	{Text_Status: 0},
	{TextInput_projectId: 0},
	{AdImage: 0},
	{Touch: 0},
	{Browser: 0},
	{Button_goToTestLayout: 0},
	{Button_back: 0},
	{TextInput_AdType: 0},
	{List_AdType: 0},
	{Button_connect_plug: 0},
	{Button_connect_II: 0},
	{Sine: 0},
	{Sprite_connect_plug: 0},
	{TextInput_RegisterProjectId: 0},
	{Button_RegisterProject: 0},
	{TextInput_AdID: 0},
	{TextInput_AdViewsExtra: 0},
	{Text_AuthStatus: 0},
	{Text_Login: 0},
	{TiledBackground: 0},
	{Sprite_X: 0},
	{Button_goTo_portrait_full: 0},
	{TextInput_TokenRecipient: 0},
	{TextInput_TokenAmount: 0},
	{Button_CheckTokenBalance: 0},
	{Button_TransferTokens: 0},
	{Text_TokenBalance: 0},
	{Text_PID: 0},
	{Button_test_transfer_from: 0},
	{Sprite_connect_internet_identity: 0},
	{Sprite_ad_network_logo: 0},
	{Sprite: 0},
	{Text_TotalViewsForProjectValue: 0},
	{Text_TotalActiveAdsValue: 0},
	{Text_TotalViewsAllProjectsValue: 0},
	{Text_RemainingViewsForAdValue: 0},
	{Text_RemainingViewsAllAdsValue: 0},
	{Button_menu: 0},
	{Input_AdID: 0},
	{Input_ProjectID: 0},
	{Button_FetchRemainingViewsAd: 0},
	{Button_FetchViewsProject: 0},
	{Text_StatusMessage: 0},
	{TextInput_Password: 0},
	{Button_VerifyPassword: 0},
	{Text_StatusPassword: 0},
	{Sprite_Monetize: 0},
	{Sprite_Advertize: 0},
	{Sprite_Create_Ad: 0},
	{Sprite_Menu: 0},
	{Sprite_Your_Dashboard: 0},
	{Button_Choose_Ad_Image: 0},
	{Sprite2: 0},
	{Sprite_Register: 0},
	{Sprite_PreviewButton: 0},
	{Sprite_YourAd_Banner: 0},
	{Sprite_ICP_Symbol: 0},
	{Sprite_Purchase_Views: 0},
	{Sprite_Go_Back: 0},
	{Button_CashOutProject: 0},
	{Button_CashOutAllProjects: 0},
	{TextInput_ProjectContact: 0},
	{Sprite_Logout: 0},
	{Text: 0},
	{Text_Views_Price: 0},
	{Sprite_Top_Up: 0},
	{Text_logging: 0},
	{Text_logging_2: 0},
	{Sprite_Mint_Icrc1: 0},
	{AdImageFullPortrait: 0},
	{Sprite_Balance_Background: 0},
	{Sprite_Send: 0},
	{Sprite6_Cash_Out: 0},
	{Sprite_Register_Project: 0},
	{Text2: 0},
	{Text_Sizes: 0},
	{Text_Sizes2: 0},
	{List_MyAds: 0},
	{Button_Choose_Ad_Image_Portrait: 0},
	{FileChooser_AdImage_Portrait: 0},
	{Button_Choose_Ad_Image_Landscape: 0},
	{FileChooser_AdImage_Landscape: 0},
	{Sprite_PreviewPortrait: 0},
	{Sprite_PreviewLandscape: 0},
	{Audio: 0},
	{Sprite_PreviewSingle: 0},
	{Sprite_required_ad_type: 0},
	{Sprite_required_adUrlInput: 0},
	{Sprite_required_adViewsInput: 0},
	{Sprite_required_imageSingle: 0},
	{Sprite_required_imagePortrait: 0},
	{Sprite_required_imageLandscape: 0},
	{Button_DeleteAd: 0},
	{TextInput_AdName: 0},
	{Sprite_required_adName: 0},
	{Sprite_YourAd_Portrait_Landscape: 0},
	{AdBase64Input: 0},
	{AdClickUrlInput: 0},
	{AdViewsInput: 0},
	{AdIDInput: 0},
	{AdViewsExtra: 0},
	{LastCreatedAdId: 0},
	{AllAdsJson: 0},
	{LastAdJson: 0},
	{StatusMessage: 0},
	{ChosenFileURL: 0},
	{projectId: 0},
	{CurrentAdBase64: 0},
	{CurrentAdClickUrl: 0},
	{AdTypeInput: 0},
	{AuthState: 0},
	{TokenBalance: 0},
	{TokenRecipient: 0},
	{TokenAmount: 0},
	{currentPrincipal: 0},
	{TotalActiveAds: 0},
	{TotalViewsForProject: 0},
	{TotalViewsAllProjects: 0},
	{RemainingViewsForAd: 0},
	{RemainingViewsAllAds: 0},
	{ProjectContactInput: 0},
	{TransferCounter: 0},
	{AdBase64InputPortrait: 0},
	{AdBase64InputLandscape: 0},
	{LandscapeImageUploaded: 0},
	{PortraitVersionUploaded: 0},
	{SingleImageUploaded: 0},
	{AdNameInput: 0},
	{isBetaTester: 0},
	{UserInputPassword: 0}
];

self.InstanceType = {
	Button_create_ad: class extends self.IButtonInstance {},
	TextInput_AdClickUrlInput: class extends self.ITextInputInstance {},
	Button_fetch_next_ad: class extends self.IButtonInstance {},
	Button_PurchaseViews: class extends self.IButtonInstance {},
	Button_show_all_ads: class extends self.IButtonInstance {},
	FileChooser_AdImage: class extends self.IFileChooserInstance {},
	TextInput_AdViewsInput: class extends self.ITextInputInstance {},
	Text_Status: class extends self.ITextInstance {},
	TextInput_projectId: class extends self.ITextInputInstance {},
	AdImage: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Button_goToTestLayout: class extends self.IButtonInstance {},
	Button_back: class extends self.IButtonInstance {},
	TextInput_AdType: class extends self.ITextInputInstance {},
	List_AdType: class extends self.IListInstance {},
	Button_connect_plug: class extends self.IButtonInstance {},
	Button_connect_II: class extends self.IButtonInstance {},
	Sprite_connect_plug: class extends self.ISpriteInstance {},
	TextInput_RegisterProjectId: class extends self.ITextInputInstance {},
	Button_RegisterProject: class extends self.IButtonInstance {},
	TextInput_AdID: class extends self.ITextInputInstance {},
	TextInput_AdViewsExtra: class extends self.ITextInputInstance {},
	Text_AuthStatus: class extends self.ITextInstance {},
	Text_Login: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite_X: class extends self.ISpriteInstance {},
	Button_goTo_portrait_full: class extends self.IButtonInstance {},
	TextInput_TokenRecipient: class extends self.ITextInputInstance {},
	TextInput_TokenAmount: class extends self.ITextInputInstance {},
	Button_CheckTokenBalance: class extends self.IButtonInstance {},
	Button_TransferTokens: class extends self.IButtonInstance {},
	Text_TokenBalance: class extends self.ITextInstance {},
	Text_PID: class extends self.ITextInstance {},
	Button_test_transfer_from: class extends self.IButtonInstance {},
	Sprite_connect_internet_identity: class extends self.ISpriteInstance {},
	Sprite_ad_network_logo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text_TotalViewsForProjectValue: class extends self.ITextInstance {},
	Text_TotalActiveAdsValue: class extends self.ITextInstance {},
	Text_TotalViewsAllProjectsValue: class extends self.ITextInstance {},
	Text_RemainingViewsForAdValue: class extends self.ITextInstance {},
	Text_RemainingViewsAllAdsValue: class extends self.ITextInstance {},
	Button_menu: class extends self.IButtonInstance {},
	Input_AdID: class extends self.ITextInputInstance {},
	Input_ProjectID: class extends self.ITextInputInstance {},
	Button_FetchRemainingViewsAd: class extends self.IButtonInstance {},
	Button_FetchViewsProject: class extends self.IButtonInstance {},
	Text_StatusMessage: class extends self.ITextInstance {},
	TextInput_Password: class extends self.ITextInputInstance {},
	Button_VerifyPassword: class extends self.IButtonInstance {},
	Text_StatusPassword: class extends self.ITextInstance {},
	Sprite_Monetize: class extends self.ISpriteInstance {},
	Sprite_Advertize: class extends self.ISpriteInstance {},
	Sprite_Create_Ad: class extends self.ISpriteInstance {},
	Sprite_Menu: class extends self.ISpriteInstance {},
	Sprite_Your_Dashboard: class extends self.ISpriteInstance {},
	Button_Choose_Ad_Image: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite_Register: class extends self.ISpriteInstance {},
	Sprite_PreviewButton: class extends self.ISpriteInstance {},
	Sprite_YourAd_Banner: class extends self.ISpriteInstance {},
	Sprite_ICP_Symbol: class extends self.ISpriteInstance {},
	Sprite_Purchase_Views: class extends self.ISpriteInstance {},
	Sprite_Go_Back: class extends self.ISpriteInstance {},
	Button_CashOutProject: class extends self.IButtonInstance {},
	Button_CashOutAllProjects: class extends self.IButtonInstance {},
	TextInput_ProjectContact: class extends self.ITextInputInstance {},
	Sprite_Logout: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text_Views_Price: class extends self.ITextInstance {},
	Sprite_Top_Up: class extends self.ISpriteInstance {},
	Text_logging: class extends self.ITextInstance {},
	Text_logging_2: class extends self.ITextInstance {},
	Sprite_Mint_Icrc1: class extends self.ISpriteInstance {},
	AdImageFullPortrait: class extends self.ISpriteInstance {},
	Sprite_Balance_Background: class extends self.ISpriteInstance {},
	Sprite_Send: class extends self.ISpriteInstance {},
	Sprite6_Cash_Out: class extends self.ISpriteInstance {},
	Sprite_Register_Project: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text_Sizes: class extends self.ITextInstance {},
	Text_Sizes2: class extends self.ITextInstance {},
	List_MyAds: class extends self.IListInstance {},
	Button_Choose_Ad_Image_Portrait: class extends self.IButtonInstance {},
	FileChooser_AdImage_Portrait: class extends self.IFileChooserInstance {},
	Button_Choose_Ad_Image_Landscape: class extends self.IButtonInstance {},
	FileChooser_AdImage_Landscape: class extends self.IFileChooserInstance {},
	Sprite_PreviewPortrait: class extends self.ISpriteInstance {},
	Sprite_PreviewLandscape: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite_PreviewSingle: class extends self.ISpriteInstance {},
	Sprite_required_ad_type: class extends self.ISpriteInstance {},
	Sprite_required_adUrlInput: class extends self.ISpriteInstance {},
	Sprite_required_adViewsInput: class extends self.ISpriteInstance {},
	Sprite_required_imageSingle: class extends self.ISpriteInstance {},
	Sprite_required_imagePortrait: class extends self.ISpriteInstance {},
	Sprite_required_imageLandscape: class extends self.ISpriteInstance {},
	Button_DeleteAd: class extends self.ISpriteInstance {},
	TextInput_AdName: class extends self.ITextInputInstance {},
	Sprite_required_adName: class extends self.ISpriteInstance {},
	Sprite_YourAd_Portrait_Landscape: class extends self.ISpriteInstance {}
}